version: '3'
services:
  app:
    container_name: ${APP_CONTAINER_NAME}
    image: peron:php8-fpm
    volumes:
      - ${ROOT_PATH}:/var/www/html
    depends_on:
      - db
    networks:
      - backend

  web:
    container_name: ${WEB_CONTAINER_NAME}
    image: nginx:stable-alpine
    ports:
      - "${WEB_PORT}:80"
    volumes:
      - ${ROOT_PATH}:/var/www/html
      - ./../nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./../nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./../nginx/module.conf/fastcgi_cache.conf.example:/etc/nginx/module.conf/fastcgi_cache.conf
    depends_on:
      - app
    networks:
      - backend

  db:
    container_name: ${DB_CONTAINER_NAME}
    image: mysql:8.0.25
    working_dir: /home
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./../../../data/mysql/db:/var/lib/mysql
      - ./../../../data/mysql/init:/home
    ports:
      - "${DB_PORT}:3306"
    networks:
      - backend
      - backend_db

  adminer:
    container_name: ${ADMINER_CONTAINER_NAME}
    image: adminer:latest
    ports:
      - "${ADMINER_PORT}:8080"
    depends_on:
      - db
    networks:
      - backend_db

networks:
  backend:
  backend_db: